#server.port=8765
#spring.application.name=TrackEye
#
## Storage Configuration
#trackeye.storage-path=${user.home}/TrackEyeData
#
## Tracking Configuration (milliseconds)
#trackeye.idle-timeout-seconds=180
#trackeye.poll-interval-ms=1000
#
## Screenshot Configuration
#trackeye.screenshot-interval-seconds=300
#trackeye.screenshot-on-app-switch=true
#
## Logging
#logging.level.com.roze=INFO
#logging.file.path=${trackeye.storage-path}/logs

server.port=8765
spring.application.name=TrackEye

# Storage Configuration
trackeye.storage-path=${user.home}/TrackEyeData

# Tracking Configuration (milliseconds)
trackeye.idle-timeout-seconds=180
trackeye.poll-interval-ms=1000

# Screenshot Configuration
trackeye.screenshot-interval-seconds=300
trackeye.screenshot-on-app-switch=true

# Browser Tracking
trackeye.browser-tracking-enabled=true
trackeye.browser-poll-interval-ms=2000

# Logging
logging.level.com.roze=INFO
logging.level.com.roze.platform=DEBUG
logging.file.path=${trackeye.storage-path}/logs

# Linux Specific
spring.main.web-application-type=servlet
server.error.include-message=always