-- V2__teams_policy_notifications.sql
-- Adds: manager assignment on users, org-configurable policy rules, recorded
-- violations, and a generic notifications table. Portable across
-- PostgreSQL and H2 (PostgreSQL mode), consistent with V1.

ALTER TABLE users ADD COLUMN IF NOT EXISTS manager_id BIGINT;
CREATE INDEX IF NOT EXISTS idx_users_manager ON users(manager_id);

CREATE TABLE IF NOT EXISTS policy_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    category VARCHAR(50) NOT NULL,
    match_type VARCHAR(50) NOT NULL,
    pattern VARCHAR(500) NOT NULL,
    severity VARCHAR(20) NOT NULL DEFAULT 'MEDIUM',
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at BIGINT NOT NULL,
    created_by BIGINT,
    CONSTRAINT fk_policy_rules_org FOREIGN KEY (organization_id) REFERENCES organizations(id)
);
CREATE INDEX IF NOT EXISTS idx_policy_rules_org ON policy_rules(organization_id);

CREATE TABLE IF NOT EXISTS policy_violations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    device_id BIGINT NOT NULL,
    rule_id BIGINT NOT NULL,
    category VARCHAR(50) NOT NULL,
    severity VARCHAR(20) NOT NULL,
    matched_value VARCHAR(1000),
    occurred_at BIGINT NOT NULL,
    CONSTRAINT fk_violations_org FOREIGN KEY (organization_id) REFERENCES organizations(id),
    CONSTRAINT fk_violations_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_violations_device FOREIGN KEY (device_id) REFERENCES devices(id)
);
CREATE INDEX IF NOT EXISTS idx_violations_org_time ON policy_violations(organization_id, occurred_at);
CREATE INDEX IF NOT EXISTS idx_violations_user ON policy_violations(user_id);

CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    recipient_user_id BIGINT NOT NULL,
    type VARCHAR(50) NOT NULL,
    title VARCHAR(255) NOT NULL,
    body VARCHAR(2000),
    subject_user_id BIGINT,
    read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at BIGINT NOT NULL,
    CONSTRAINT fk_notifications_org FOREIGN KEY (organization_id) REFERENCES organizations(id),
    CONSTRAINT fk_notifications_recipient FOREIGN KEY (recipient_user_id) REFERENCES users(id)
);
CREATE INDEX IF NOT EXISTS idx_notifications_recipient ON notifications(recipient_user_id, read);
